services:
  db:
    image: postgres:16
    container_name: todo_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - todo_pgdata:/var/lib/postgresql/data
    networks:
      - todo_net
  app:
    image: tg/todo-app:1.2
    container_name: todo_app
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
    networks:
      - todo_net

volumes:
  todo_pgdata:

networks:
  todo_net:
    driver: bridge
